name = "PodMack"
author = "TropicalTampico"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29497e67ed568c459e139a346fe7ecf0061b4075c6933167af32e3996fd446d0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
