name = "PodMack"
author = "TropicalTampico"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ce17687e19ada8fc2f7522d534f6d82d92e706dd34e962e59ddf35d4887614d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
