#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 17 20:01:03 MST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=miniature-shader-2.18.12.zip
